### ISSUE TITLE
Error while installing Fancy on rbx-head

### ISSUE THREAD

**Issue by weirdpercent** [bakkdoor/fancy#78]
Error output http://gist.github.com/weirdpercent/9222555

**Comment by bakkdoor** [comment]
The latest version of Rubinius has had some recent changes which broke Fancy's bootstrapping process. I will look into those over the weekend or next week (pretty busy this week). It should work with rbx 2.1.0 though.
Thanks for the report.

**Comment by bakkdoor** [comment]
Sorry for the delay, I was pretty busy the past month.
I pushed a couple of commits that should allow you to build fancy with rbx v2.2.6
I haven't tried with latest master yet, but I'll stick with the latest official release for now.

**Comment by bakkdoor** [comment]
Just checked with rbx-head and it works on my machine.

**Comment by weirdpercent** [comment]
Gave it another try and rake aborted with this: http://gist.github.com/weirdpercent/9993669 I should mention that I'm trying this on Linux running on Virtualbox within Windows. My platform can be flaky for this reason. I'll try booting into Linux proper and test it there. Thanks.

**Comment by weirdpercent** [comment]
Booted into actual Linux, no Virtualbox, did a fresh install of rvm and rbx-head and got the same NoMethodError: undefined method `bright' on an instance of String in kernel/delta/kernel.rb:78.

**Comment by bakkdoor** [comment]
Do you have Fancy's dependencies installed via bundler?
Try `bundle install` from within fancy's root dir or install the `rainbow` gem yourself.
It seems to have problems finding the String#bright method, which gets defined if the rainbow gem can't be found here: https://github.com/bakkdoor/fancy/blob/master/Rakefile#L1-12

**Comment by weirdpercent** [comment]
It's the strangest thing, I made sure the rainbow gem was installed, even uninstalled and reinstalled it, did a rake clean, then rake. It's likely some weird problem on my end. Just for giggles, here's the output: http://gist.github.com/weirdpercent/10186077

**Comment by bakkdoor** [comment]
Hey, I changed the Rakefile a bit today and now it also builds again fine on travis.
Could you please try to build the latest version on master?

**Comment by weirdpercent** [comment]
Success! Thanks Christopher, keep up the great work!

**Comment by bakkdoor** [comment]
Cool, let me know if you have any other issues or questions.
